FROM ubuntu:xenial

RUN \
  apt-get -qq update \
  && apt-get install -y software-properties-common \
  && add-apt-repository ppa:gophers/archive \
  && apt-get install -y golang-1.9-go \
  && apt-get clean

ENV PATH="/usr/lib/go-1.9/bin:${PATH}"
